server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: true #表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://eureka7002.com:7002/eureka
#      defaultZone: http://eureka7001.com:7001/eureka
  server:
    enable-self-preservation: false	#关闭eureka server自我保护机制，保证不可用服务及时剔除(默认是true)
    eviction-interval-timer-in-ms: 2000 #设置为2秒